package jpa.entity;

import jakarta.persistence.*;
import jpa.support.JpaTestSupport;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Demonstrates a basic persistent entity with an identity generated by PostgreSQL.
 */
class EntityTest {
    @Test
    void persistsAndFindsEntity() {
        try (var support = new JpaTestSupport(Customer.class)) {
            Customer customer = new Customer("Ada");
            support.transaction(em -> em.persist(customer));
            try (var em = support.em()) {
                assertEquals("Ada", em.find(Customer.class, customer.id).name);
            }
        }
    }
}

@Entity
class Customer {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
    String name;
    protected Customer() {}
    Customer(String name) { this.name = name; }
}
